### ISSUE TITLE
DNA_sampleID_format causing warnings for every other node than OUS

### ISSUE THREAD

**Issue by tinavisnovska** [InPreD/PRONTO#15]
version PRONTO-1.0

Due to the definition of the `DNA_sampleID_format` on line 953, every other node other than OUS is getting the warnings that their sampleIDs are not following the InPreD nomenclature regardless of whether they do or don't because their samples do not start with "IPD".

**Comment by xiaoliz0** [comment]
This is the sample ID naming format rule I received earlier. You still get the report generated. You could bring this topic to next bioinformatics meeting for further discussion. :)
