### ISSUE TITLE
no license in the repository

### ISSUE THREAD

**Issue by tinavisnovska** [InPreD/PRONTO#21]
It would be good to put some of license on it (probably a permissive one) and to decide how the ownership will be stated inthere - should it be a list of names or rather InPreD as a collective name?

I think that MIT license could work just fine, but I am not sure who everyone should be involved in agreeing on these particularities. 

As the repository is public, I think this should be resolved without postponing too much.

**Comment by marrip** [comment]
I think we should go with GNU General Public License v3.0. I think MIT allows for commercialising if code is reused wil GPL forces it to be open-source if reused which is better I think :relaxed:

**Comment by xiaoliz0** [comment]
A GNU General Public License v3 is added in the develop branch.

**Comment by marrip** [comment]
Awesome, thanks, Xiaoli! 👍
