### ISSUE TITLE
PRONTO failing without clear error message when encountering an empty small variant table

### ISSUE THREAD

**Issue by marrip** [InPreD/PRONTO#23]
We had a problem with an empty variant table today. We had a sample with a small amount of reads and were not aware of it (got LocalApp results with only 2 variants which were filtered out leaving no variants in the small variants table). When we ran PRONTO, we just got this error message:

```bash
Traceback (most recent call last):
File "/pronto/Script/PRONTO.py", line 1326, in <module>
main(sys.argv[1:])
File "/pronto/Script/PRONTO.py", line 1099, in main
all_data_config_DepthTumor_DNA = filter_depth_tumor_all_col(all_data,filter1_min_depth_tumor_DNA)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/pronto/Script/PRONTO.py", line 189, in filter_depth_tumor_all_col
data.append(data_config[0])
            ~~~~~~~~~~~^^^
IndexError: list index out of range
[ERR]: Errors creating PRONTO files. Exiting now ...
```

I would opt for checking that the file actually contains something before trying to give it to `filter_depth_tumor_all_col()` which then fails. The error message should state the file path and maybe sample id.

**Comment by xiaoliz0** [comment]
This is fixed in the updated script.

**Comment by gertrudeln** [comment]
Hello @xiaoliz0 , i see you closed this issue and mentioned that it is fixed in the updated script. 
We are using v1.2.0 and still facing the same error...

```
Traceback (most recent call last):
  File "/pronto/Script/PRONTO.py", line 1337, in <module>
    main(sys.argv[1:])
  File "/pronto/Script/PRONTO.py", line 1108, in main
    all_data_config_DepthTumor_DNA = filter_depth_tumor_all_col(all_data,filter1_min_depth_tumor_DNA)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pronto/Script/PRONTO.py", line 189, in filter_depth_tumor_all_col
    data.append(data_config[0])
                ~~~~~~~~~~~^^^
IndexError: list index out of range

```

Can you please look into this? Thank you

**Comment by xiaoliz0** [comment]
Hello,
Yes, this is fixed in the branch develop_OUS. I will create a push request and you could check the overview.
