### ISSUE TITLE
tagged images not available on dockerhub

### ISSUE THREAD

**Issue by marrip** [InPreD/PRONTO#24]
Somehow the new version tags are not available on dockerhub. I assume the action is not triggered for some reason. Do you tag versions locally and push them or do you tag them directly in github?

**Comment by marrip** [comment]
ah, I see the problem. You are using different kind of versions than [standard](https://semver.org/). Please adhere to the standard when you tag meaning your versions should be: `v1.0.0` which is basically `v` for version and then `major.minor.patch`. One could omit the v prefix but you are using it alread in the past tags so let's keep it.

**Comment by xiaoliz0** [comment]
I have released a new version 1.2.0 which fixed some bugs and issues reported. Is this version working in dockerhub now?
