### ISSUE TITLE
suggestion: treat the empty lines in the metadata file the same way as comments

### ISSUE THREAD

**Issue by tinavisnovska** [InPreD/PRONTO#30]
It would be convenient if empty lines are considered to be comments in the metadata file...

**Comment by xiaoliz0** [comment]
Emm, I think if you start a line with "#", the script should treat it as a comment line and ignore it in the meta file.

**Comment by xiaoliz0** [comment]
Okay, I see. This should be okay with a small update in the script. I will open this issue and implement it in the next releasing then. :)
