### ISSUE TITLE
In/InPreD_PRONTO_metadata.txt

### ISSUE THREAD

**Issue by tinavisnovska** [InPreD/PRONTO#8]
add into the file documentation that a line needs to be added for each DNA sample as well as RNA sample that should be used in the report generation process.

also for possible parallelisation of the report generating process - executing the script once for each patient - it would be great if the metadata file name could be provided as an input parameter and not to be hardcoded in the script.

**Comment by xiaoliz0** [comment]
Fixed: PRONTO will give a warning message when the RNA smaple ID is missing in the meta file but existing int the SOPPI results. Still generate the report without sample material ID of RNA.
