### ISSUE TITLE
add expected file names into a ChangeLog when they changed

### ISSUE THREAD

**Issue by tinavisnovska** [InPreD/PRONTO#9]
for example:

a file called ${DNA_SAMPLE_ID}_small_variant_table_forQC.tsv

It would be good to know about all files and file default names which are expected by the tool, especially the files which need to be created manually.

Also, it would be nice to have all fallbacks documented (as when *small_variant_table_forQC.tsv is not present, *small_variant_table.tsv is used automatically).

**Comment by xiaoliz0** [comment]
PRONTO reads ${DNA_SAMPLE_ID}_small_variant_table.tsv if the file ${DNA_SAMPLE_ID}_small_variant_table_forQC.tsv does not exist in the post-processing result folder.
